version: "3"
services:
  db:
    image: postgres
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - static:/usr/src/app/static_root
      - media:/usr/src/app/media
    depends_on:
      - api
      - client

volumes:
  static:
  media:
  pgdata:
